from . import wizard_create_quotation
from . import wizard_revision
from . import wizard_technical
from . import wizard_desing
from . import wizard_approved
from . import wizard_rejected
from . import wizard_rejected_t
from . import wizard_rejected_d
from . import wizard_pantone